### PR TITLE
Update project

### PR DESCRIPTION
**Pull request by Josh-McFarlin**
- Fix various security issues from outdated packages
- Replace custom auth with Iron-Session
- Use CSS Modules
- Update project structure to meet modern Next.js design patterns
- Merge API routes to reduce Lambda usage

### CODE REVIEW

**Comment by karpawich** [comment]
Love to see it

**Comment by Josh-McFarlin** [comment]
@karpawich 

> Love to see it

NPP!

**Comment by Josh-McFarlin** [comment]
Project is ready to be deployed. Tested and works identically to existing deployment.

**Review by Fattimo — APPROVED** [review]
👍

**Pull request merged**
